" disable system-wide filetype plugins.
let b:did_ftplugin=1

filetype plugin on
syntax on

set background=dark
set backspace=2
set cursorline
set expandtab
set incsearch
set laststatus=2
set nohlsearch
set nostartofline
set novisualbell
set nowrap
set number
set shiftwidth=2
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]
set tabstop=2

" vger
imap <F2> Signed-off-by: Sam Hansen <solid.se7en@gmail.com>

nmap <F3> :setlocal spell! spelllang=en_us<CR>
imap <F3> <Esc>:setlocal spell! spelllang=en_us<CR>i


highlight ExtraWhitespace ctermbg=red
match ExtraWhitespace /\s\+$/
